# Silicon Shepherd Configuration File
# This file contains default values for GPU occupation parameters
# You can modify these values to customize the default behavior

# GPU Configuration
gpus: [0, 1, 2, 3]          # List of GPU indices to use by default
memory: 38.0                # Memory size to occupy per GPU in GB

# Threshold and Timing Configuration  
mem_threshold: 1.0          # Memory threshold in GB - occupy when all GPU used memory < threshold
wait_minutes: 5.0           # Wait time after GPUs meet threshold (minutes)
refresh_minutes: 1.0        # GPU status check interval (minutes)

# Compute Configuration
compute_min: 30.0           # Duration of each compute cycle (minutes)
sleep_min: 5.0              # Sleep time between compute cycles (minutes)
no_compute: false           # Set to true to disable compute workload by default

# Advanced Configuration
log_level: "INFO"           # Logging level: DEBUG, INFO, WARNING, ERROR
max_retries: 3              # Maximum retries for GPU memory allocation

# Notes:
# - Command line arguments will override these default values
# - Boolean values: true/false (lowercase)
# - List values: use YAML list syntax [item1, item2, item3]
# - Float values: use decimal notation (e.g., 1.0, not 1)